site_name: DAB V2.0
site_url: https://mcjohnffs.github.io/

theme:
    name: readthedocs
markdown_extensions:
    - admonition
nav:
 - Home: 'index.md'
 - Hard- und Software Konfiguration: Hard- und Software Knfiguration.markdown
 - Installation der Entwicklungsumgebung: Installation der Entwicklungsumgebung.markdown
 - Code Beschreibung: index.md
 - BM83 Anleitung: bm83.md
 - Testsoftware: Testsoftware.markdown
 - Source Code: 'Files\_d_a_b__2___v0_81_8ino.md'
 - Datenblätter: Datenblätter.markdown
 - Quellen: Quellen.markdown
 